# -*- coding: utf-8 -*-
"""caesar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1POMwOUjQBLgh5xr5k9uSGJ3SGLNEMRFo
"""

input_string = input("Enter the string : ")
key=int(input("Enter the key between 1-25"))
cipher_text=[]
for i in (input_string):
  temp=ord(i)
  if temp > 96 and temp<123:
    temp=temp+key
    if temp>122:
      temp=temp-26
    temp=chr(temp)
    cipher_text.append(temp)
  elif temp>64 and temp<91:
    temp=temp+key
    if temp>90:
      temp=temp-26;
    temp=chr(temp)
    cipher_text.append(temp)
print(cipher_text)